services:
  - type: web
    name: expense-tracker-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn expense_tracker_backend.wsgi:application"
    autoDeploy: true